/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MetodosGerente.operacionesGerente;
import USUARIOS.colaborador;
import javax.swing.JOptionPane;

/**
 *
 * @author Jasson
 */
public class agregarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form agregarEmpleado
     */
    public agregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_agregarEmpleado = new javax.swing.JLabel();
        jLabel1_nombre = new javax.swing.JLabel();
        jLabel2_edad = new javax.swing.JLabel();
        jLabel3_celular = new javax.swing.JLabel();
        jLabel4_usuario = new javax.swing.JLabel();
        jLabel5_contraseña = new javax.swing.JLabel();
        jTextField1_nombre = new javax.swing.JTextField();
        jTextField2_edad = new javax.swing.JTextField();
        jTextField3_celular = new javax.swing.JTextField();
        jTextField4_usuario = new javax.swing.JTextField();
        jTextField5_contraseña = new javax.swing.JTextField();
        jButton1_agregar = new javax.swing.JButton();
        jButton1_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_agregarEmpleado.setText("Registrar nuevo empleado");

        jLabel1_nombre.setText("Nombre:");

        jLabel2_edad.setText("Edad:");

        jLabel3_celular.setText("Número celular:");

        jLabel4_usuario.setText("Usuario:");

        jLabel5_contraseña.setText("Contraseña:");

        jTextField1_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_nombreActionPerformed(evt);
            }
        });

        jButton1_agregar.setText("Agregar");
        jButton1_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_agregarActionPerformed(evt);
            }
        });

        jButton1_salir.setText("Salir");
        jButton1_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1_agregarEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3_celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2_edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2_edad, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(jTextField3_celular)
                                        .addComponent(jTextField4_usuario)
                                        .addComponent(jTextField5_contraseña))
                                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 125, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1_salir)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_agregarEmpleado)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_nombre)
                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_edad)
                    .addComponent(jTextField2_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_celular)
                    .addComponent(jTextField3_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4_usuario)
                    .addComponent(jTextField4_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_contraseña)
                    .addComponent(jTextField5_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_agregar)
                    .addComponent(jButton1_salir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_nombreActionPerformed

    private void jButton1_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_agregarActionPerformed
        colaborador trabajador = new colaborador();
        trabajador.setNombre(jTextField1_nombre.getText());
        trabajador.setEdad(Integer.parseInt(jTextField2_edad.getText()));
        trabajador.setNumeroCelular(Integer.parseInt(jTextField3_celular.getText()));
        trabajador.setUsuario(jTextField4_usuario.getText());
        trabajador.setContraseña(jTextField5_contraseña.getText());

        operacionesGerente agregar = new operacionesGerente();

        if (agregar.agregarEmpleado(trabajador) == 1) {
            JOptionPane.showMessageDialog(this, "Trabajador insertado");
        } else {
            JOptionPane.showMessageDialog(this, "Trabajador ya existe");
        }
        jTextField1_nombre.setText("");
        jTextField2_edad.setText("");
        jTextField3_celular.setText("");
        jTextField4_usuario.setText("");
        jTextField5_contraseña.setText("");
    }//GEN-LAST:event_jButton1_agregarActionPerformed

    private void jButton1_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1_salirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_agregar;
    private javax.swing.JButton jButton1_salir;
    private javax.swing.JLabel jLabel1_agregarEmpleado;
    private javax.swing.JLabel jLabel1_nombre;
    private javax.swing.JLabel jLabel2_edad;
    private javax.swing.JLabel jLabel3_celular;
    private javax.swing.JLabel jLabel4_usuario;
    private javax.swing.JLabel jLabel5_contraseña;
    private javax.swing.JTextField jTextField1_nombre;
    private javax.swing.JTextField jTextField2_edad;
    private javax.swing.JTextField jTextField3_celular;
    private javax.swing.JTextField jTextField4_usuario;
    private javax.swing.JTextField jTextField5_contraseña;
    // End of variables declaration//GEN-END:variables
}
