/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Jose
 */
import GUI.colaboradorGUI;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class colaboradorGUI extends javax.swing.JFrame {

    /**
     * Creates new form colaboradorGUI
     */
    public colaboradorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        colaboradorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1_ingresarCliente = new javax.swing.JButton();
        jButton2_eliminarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2_venderBoletos = new javax.swing.JButton();
        iconoColaborador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1_agregarBusOTren = new javax.swing.JButton();
        jButton1_agregarRuta = new javax.swing.JButton();
        jButton_tiquetesVendidos = new javax.swing.JButton();
        jButton1_modificarUnidades = new javax.swing.JButton();
        jButton2_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colaboradorLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        colaboradorLabel.setText("Colaboradores");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1_ingresarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_ingresarCliente.setText("Ingresar Cliente");
        jButton1_ingresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ingresarClienteActionPerformed(evt);
            }
        });

        jButton2_eliminarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2_eliminarCliente.setText("Eliminar Cliente");
        jButton2_eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_eliminarClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Opciones de clientes");

        jButton2_venderBoletos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2_venderBoletos.setText("Vender boletos");
        jButton2_venderBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_venderBoletosActionPerformed(evt);
            }
        });

        iconoColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1057de025504e2a.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2_eliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2_venderBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_ingresarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoColaborador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1_ingresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_eliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_venderBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Opciones rutas/tiquetes");

        jButton1_agregarBusOTren.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_agregarBusOTren.setText("Nuevo bus/tren");
        jButton1_agregarBusOTren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_agregarBusOTrenActionPerformed(evt);
            }
        });

        jButton1_agregarRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_agregarRuta.setText("Nueva ruta");
        jButton1_agregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_agregarRutaActionPerformed(evt);
            }
        });

        jButton_tiquetesVendidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_tiquetesVendidos.setText("Tiquetes Vendidos");
        jButton_tiquetesVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tiquetesVendidosActionPerformed(evt);
            }
        });

        jButton1_modificarUnidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1_modificarUnidades.setText("Modificar Unidades");
        jButton1_modificarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_modificarUnidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_tiquetesVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(jButton1_modificarUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(jButton1_agregarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_agregarBusOTren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jButton1_agregarBusOTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_agregarRuta)
                .addGap(42, 42, 42)
                .addComponent(jButton1_modificarUnidades)
                .addGap(43, 43, 43)
                .addComponent(jButton_tiquetesVendidos)
                .addGap(77, 77, 77))
        );

        jButton2_salir.setText("Salir");
        jButton2_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(colaboradorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2_salir)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colaboradorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2_salir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_ingresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ingresarClienteActionPerformed
        this.dispose();
        int opcion=2;
        agregarCliente nuevoCliente = new agregarCliente(opcion);
        nuevoCliente.setVisible(true);
        nuevoCliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1_ingresarClienteActionPerformed

    private void jButton_tiquetesVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tiquetesVendidosActionPerformed
        this.dispose();
        int tipoReporte = 1;
        String rutaArchivo = "Diairio.txt";
        resultadoGUI resul = new resultadoGUI(tipoReporte, rutaArchivo);
        resul.setVisible(true);
        resul.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton_tiquetesVendidosActionPerformed

    private void jButton1_agregarBusOTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_agregarBusOTrenActionPerformed
        this.dispose();
        unidadesGUI nuevaUnidad = new unidadesGUI();
        nuevaUnidad.setVisible(true);
        nuevaUnidad.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1_agregarBusOTrenActionPerformed

    private void jButton2_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_salirActionPerformed
        this.dispose();
        menuLogin login = new menuLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2_salirActionPerformed

    private void jButton1_agregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_agregarRutaActionPerformed
        this.dispose();
        agregarRutasGUI nuevaRuta = new agregarRutasGUI();
        nuevaRuta.setVisible(true);
        nuevaRuta.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton1_agregarRutaActionPerformed

    private void jButton2_eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_eliminarClienteActionPerformed
        try {
            this.dispose();
            Gui_1 eliminarClientes = new Gui_1();
            eliminarClientes.setVisible(true);
            eliminarClientes.setLocationRelativeTo(null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2_eliminarClienteActionPerformed

    private void jButton2_venderBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_venderBoletosActionPerformed
        this.dispose();
        venderGUI venderEjec = new venderGUI();
        venderEjec.setVisible(true);
        venderEjec.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton2_venderBoletosActionPerformed

    private void jButton1_modificarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_modificarUnidadesActionPerformed
        try {
            this.dispose();
            Gui_2 gui_2 = new Gui_2();
            gui_2.setVisible(true);
            gui_2.setLocationRelativeTo(null);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1_modificarUnidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(colaboradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(colaboradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(colaboradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(colaboradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //+10
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new colaboradorGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colaboradorLabel;
    private javax.swing.JLabel iconoColaborador;
    private javax.swing.JButton jButton1_agregarBusOTren;
    private javax.swing.JButton jButton1_agregarRuta;
    private javax.swing.JButton jButton1_ingresarCliente;
    private javax.swing.JButton jButton1_modificarUnidades;
    private javax.swing.JButton jButton2_eliminarCliente;
    private javax.swing.JButton jButton2_salir;
    private javax.swing.JButton jButton2_venderBoletos;
    private javax.swing.JButton jButton_tiquetesVendidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
