/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JTable;

/**
 *
 * @author Jasson
 */
public class listaTrabajadores extends javax.swing.JFrame {

    /**
     * Creates new form listaTrabajadores
     */
    public listaTrabajadores() {
        initComponents();
        String[] columnasTrabajadores = {
            "Nombre:",
            "Edad:",
            "Celular:",
            "Usuario:",
            "Contraseña:"
        };
        String rutaArchivo = "Trabajadores.txt";
        File fileTrabajador = new File(rutaArchivo);

        int filasTrabajadores = 0;

        try {
            if (!fileTrabajador.exists()) {
                fileTrabajador.createNewFile();
            }
            FileReader fileR = new FileReader(fileTrabajador);
            BufferedReader buffReader = new BufferedReader(fileR);
            while ((buffReader.readLine()) != null) {

                filasTrabajadores++;
            }
        } catch (Exception e) {
        }

        Object[][] datosTrabajadores = new Object[filasTrabajadores][5];
        try {
            if (!fileTrabajador.exists()) {
                fileTrabajador.createNewFile();
            }

            String cadena = "";
            FileReader fileR = new FileReader(fileTrabajador);
            BufferedReader buffReader = new BufferedReader(fileR);

            filasTrabajadores = 0;

            while ((cadena = buffReader.readLine()) != null) {
                if (cadena.indexOf(",") != -1) {
                    datosTrabajadores[filasTrabajadores][0] = cadena.split(",")[0];
                    datosTrabajadores[filasTrabajadores][1] = cadena.split(",")[1];
                    datosTrabajadores[filasTrabajadores][2] = cadena.split(",")[2];
                    datosTrabajadores[filasTrabajadores][3] = cadena.split(",")[3];
                    datosTrabajadores[filasTrabajadores][4] = cadena.split(",")[4];
                }
                filasTrabajadores++;
            }
        } catch (Exception e) {
        }

        JTable tableDiario = new JTable(datosTrabajadores, columnasTrabajadores);
        this.setLayout(new BorderLayout());
        this.add(tableDiario.getTableHeader(), BorderLayout.PAGE_START);
        this.add(tableDiario, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(Salir)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
}
